expense_groups:
  Services: ["SERVI‚O", "RESTAURANTE"]
  Necessities: [ "SUPERMERCADOS", "FARMACIAS", "POSTO DE GAS", "M.O.T.O."]
  Discretionary: ["VAREJO", "VESTUARIO", "ARTIGOS ELETRO", "MOVEIS E DECOR", "AUTO PE‚AS", "JOALHERIA"]
  Travel: ["CIA AEREAS", "HOTEIS", "AGENCIA DE TUR"]